name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: ./android/gradlew assembleDebug
    - name: Firebase App Distribution Action
      # You may pin to the exact commit or the version.
      # uses: hasretsariyer/firebase-app-distribution-github-action@1efdc61b2aecd54be4072edb5dd527be26571943
      uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
      with:
        # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
        app_id: 1:225326205932:android:4d1855672f9e57c36a8ec9
        # Path of IPA or APK file to distribution.
        app_file: ./android/app/build/outputs/release/app-release.apk
        # 'Firebase access token. You can create it by `firebase login:ci` on your local machine.
        firebase_token: 1//03CW1kulJyWWVCgYIARAAGAMSNwF-L9IrsdICmiWSbesG4l473wbwwdeHYlCDBwYwV1Iv9nQ8JW1Yh3wj5gtdWtNjtd2fBe1qDVQ
        # Distribution groups
        tester_groups: myawesomeapp-android
